name: CI - Docker + Pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build de los servicios
        run: docker compose -f docker-compose.yml build

      - name: Levantar servicios en segundo plano
        run: docker compose -f docker-compose.yml up -d

      - name: Esperar a que la base de datos esté lista
        run: sleep 15

      - name: Ejecutar tests dentro del contenedor
        run: docker compose exec -T app pytest tests

      - name: Apagar servicios
        run: docker compose down -v
