name: CI - Docker + Pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d app_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build de los servicios
        run: docker compose -f docker-compose.yml build

      - name: Esperar a que la base de datos esté lista
        run: |
          echo "Esperando 15 segundos que postgres esté disponible..."
          sleep 15

      - name: Levantar servicios en segundo plano
        run: docker compose up -d

      - name: Ejecutar tests dentro del contenedor
        run: docker compose exec -T app pytest tests

      - name: Apagar servicios
        run: docker compose down -v
